server:
  port: 8081
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    username: root
    password: abc1392786**
    url: jdbc:mysql://106.55.180.208:3306/pzforest?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
webconfig:
  path: /var/wwwroot/image/
qq:
  id: 2138805098
  password: aaa86925876
logging:
  file:
    path: /var/wwwroot/