server:
  port: 8088
spring:
  redis:
    host: 192.168.2.14
    port: 6379
  datasource:
    username: root
    password: abc1392786**
    url: jdbc:mysql://106.55.180.208:3306/pzforest?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
webconfig:
  path: D:/
qq:
  id: 437793081
  password: ddd492843929
logging:
  file:
    path: D:/log